trigger:
 batch: true
 branches:
   include:
     - master
 paths:
   include:
     - /users-app
name: $(date:yyyy.MM.dd)$(rev:.r)
stages:
- stage: _default
  jobs:
  - job: Job
    displayName: 'users app'
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Npm@1
      displayName: 'npm install'
      inputs:
        workingDir: './users-app'
        verbose: false
    - task: Npm@1
      displayName: 'Build'
      inputs:
        command: custom
        verbose: false
        workingDir: './users-app'
        customCommand: 'run build'
    - task: CopyPublishBuildArtifacts@1
      inputs:
        CopyRoot: ./users-app/dist
        Contents: '**'
        ArtifactName: 'drop'
        ArtifactType: 'Container'
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'drop'
        targetPath: './users-app/dist'
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Visual Studio Enterprise Subscription – MPN(Arun & kondivenkat)(41f7b0ed-25c5-40f5-a269-11adeb631715)'
        appType: 'webApp'
        WebAppName: 'multi-stage-pipeline'
        packageForLinux: './users-app/dist'